### PR TITLE
Add a .travis.yml file for regressible checking of OSS-Fuzz

### PR DESCRIPTION
**Pull request by cmeister2**

### CODE REVIEW

**Comment by kevina** [comment]
I noticed this in the logs:
```
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```
I take it that is by design?

**Comment by cmeister2** [comment]
Yep, that's just what happens when you pass an input file to the fuzzer.

**Comment by kevina** [comment]
Does this check to make sure that the coverage build(s) will succeed?

**Comment by kevina** [comment]
Also I think you should just remove this or return a non-zero exit code:
```
if [[ ! -d /tmp/ossfuzz/projects/${PROJECT_NAME} ]]
then
    echo "Could not find the ${PROJECT_NAME} project in ossfuzz"

    # Exit with a success code while the aspell project is not expected to exist
    # on oss-fuzz.
    exit 0
fi
```
Sorry if I misunderstand the intent of the code.

**Comment by cmeister2** [comment]
> 
> 
> Does this check to make sure that the coverage build(s) will succeed?

This does not check that currently, no.

> 
> 
> Also I think you should just remove this or return a non-zero exit code:
> 
> ```
> if [[ ! -d /tmp/ossfuzz/projects/${PROJECT_NAME} ]]
> then
>     echo "Could not find the ${PROJECT_NAME} project in ossfuzz"
> 
>     # Exit with a success code while the aspell project is not expected to exist
>     # on oss-fuzz.
>     exit 0
> fi
> ```
> 
> Sorry if I misunderstand the intent of the code.

Nope, you're totally correct. I'll edit this now.

**Comment by kevina** [comment]
>> Does this check to make sure that the coverage build(s) will succeed?
>
> This does not check that currently, no.

Would it be possible to add it?  I _think_ you can do that with `python infra/helper.py build_fuzzers --sanitizer coverage $PROJECT_NAME` according to https://google.github.io/oss-fuzz/getting-started/new-project-guide/

> Nope, you're totally correct. I'll edit this now.

Thanks.

**Comment by cmeister2** [comment]
Sure, I'll look into it

**Comment by cmeister2** [comment]
@kevina I added coverage and afl-asan to be more complete.

**Review by kevina — APPROVED** [review]

**Pull request merged**
